### ISSUE TITLE
How to set custom values for CSS properties

### ISSUE THREAD

**Issue by nor0x** [BlazorComponents/MatBlazor#29]
thanks for the components - I really enjoy experimenting with them.

I was wondering if there is a way to set custom values for CSS properties like `--mdc-theme-primary`?
It would be nice to control the overall look of the components by setting a global property.

**Comment by nor0x** [comment]
I was able to override the values in a regular .css file 

```
:root {
    --mdc-theme-primary: #488cff;
    --mdc-theme-secondary: #ffff8c;
  }
```

**Comment by Jasoneng2017** [comment]
> 我能够覆盖常规.css文件中的值
> 
> ```
> :root {
>     --mdc-theme-primary: #488cff;
>     --mdc-theme-secondary: #ffff8c;
>   }
> ```
why i can't find this file?could u share the method for details ?
