### ISSUE TITLE
Error since adding MatBlazor: The types BlazorWebAssemblyHost and IWebAssemblyHostBuilder exist in two assemblies

### ISSUE THREAD

**Issue by BenjaminCharlton** [BlazorComponents/MatBlazor#30]
Hello MatBlazor developers!

Blazor and MatBlazor are both great ideas. I'm experimenting with them at the moment in a Blazor 
 app using v 0.9.0 Preview 3 of Blazor.

Since I installed the MatBlazor library (latest stable v 0.4.5 from Nuget) it has introduced a compilation error into my project. The error is below:

`Error CS0433 The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=0.9.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	BlazorClient	C:\Users\USER\BlazorClient\Program.cs	12`

And here is line 12-16 of Program.cs (which I have not changed - it's just from the template)

```
        public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args)
        {
            return BlazorWebAssemblyHost.CreateDefaultBuilder()
                .UseBlazorStartup<Startup>();
        }
```

Fully qualifying the names of these two classes (IWebAssemblyHostBuilder and BlazorWebAssemblyHost) did not help. I guess because they're exactly the same classes in the same namespaces but have moved from one DLL to another.

Can anybody assist with this error please?

Many thanks in advance!

Benjamin

**Comment by engineX** [comment]
As I know MatBlazor was not updated to latest version of Blazor 0.9.
I guess @SamProf  will update it soon.

**Comment by BenjaminCharlton** [comment]
I hope so! It would be great to be able to use it again!

**Comment by SamProf** [comment]
> I hope so! It would be great to be able to use it again!

I think will fix this today or tomorrow.

**Comment by SamProf** [comment]
Hello!

Now, on nuget available new version of MatBlazor 0.5
https://www.nuget.org/packages/MatBlazor/0.5.0

Work is not completed, some components still not works, but in general you can try to use MatBlazor with new Blazor 0.9.
Tomorrow I will try to fix all components.

Also in nearest feature I will improve and add new components.

**Comment by BenjaminCharlton** [comment]
Thank you for your efforts on this and thank you for notifying us of your progress here, @SamProf!

**Comment by SamProf** [comment]
Now, I have made my upgraded release MatBlazor 0.6. (Upgraded to Blazor 0.9) and fix some problems.
I have started to test with Razor Components Application.

So, now MatBlazor works with client side Blazor 0.9.

I found that Razor Component Application not loaded empbedded resource content from my library - so, I need few days to fix this.
Also I have started new sprint to develop more components and imprrove existsing.
Thank you.

**Comment by BenjaminCharlton** [comment]
Great news! Thanks for your efforts and keeping us updated.

**Comment by SamProf** [comment]
Hey!

I introduce v 0.6.1 with supporting Razor Components.
At the beginning of the your application, usually in MainLayout.cshtml please add MatBlazorInstall component
Thank you.

**Comment by tedekeroth** [comment]
@SamProf Thanks for MatBlazor =) However, the error described above still exists:

> The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.5.1.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.AspNetCore.Blazor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

This happened when I added the [https://www.nuget.org/packages/Cloudcrate.AspNetCore.Blazor.Browser.Storage/](https://www.nuget.org/packages/Cloudcrate.AspNetCore.Blazor.Browser.Storage/) package.

What am I missing? =)

**Comment by SamProf** [comment]
It's not because MatBlazor. You use old version of Cloudcrate.AspNetCore.Blazor.Browser.Storage

Latest is https://www.nuget.org/packages/Cloudcrate.AspNetCore.Blazor.Browser.Storage/3.0.0-preview5-19227-02

Conflict of versions of Blazor.

**Comment by tedekeroth** [comment]
Oh, I was using NuGet, and NuGet suggested 0.51 as the "latest stable", like this the attached picture. There isnt much I can do (I think) in the NuGet manager, I can only choose from the list, and 0.5.1 is the latest?
![Image 006](https://user-images.githubusercontent.com/10088477/58472217-13b78980-8146-11e9-8ce5-6c26e49f6975.png)

**Comment by SamProf** [comment]
you should include prereleases 
![image](https://user-images.githubusercontent.com/5611593/58472427-86286980-8146-11e9-8441-1642f368ae39.png)

**Comment by tedekeroth** [comment]
Aha, thanks a lot for the info, got it and it works =)
