### ISSUE TITLE
Razor Components

### ISSUE THREAD

**Issue by Mercurial** [BlazorComponents/MatBlazor#32]
It seems the library breaks if I try to use it in razor components? can anyone help?

**Comment by SamProf** [comment]
In a few days (1-3) will be release with full supporting Blazor 0.9 and then will be tested in server side.

**Comment by Mercurial** [comment]
awesome! @SamProf this is the best Material Implementation I've seen so far by the way keep it up! I will try to contribute also, I was planning to implement Material Web from Google to Blazor but you done great!

**Comment by SamProf** [comment]
Now, I have made my upgraded release MatBlazor 0.6. (Upgraded to Blazor 0.9) and fix some problems.
I have started to test with Razor Components.

**Comment by SamProf** [comment]
I found that Razor Component Application not loaded empbedded resource content from my library - so, I need few days to fix this.
Also I have started new sprint to develop more components and imprrove existsing.
Thank you.

**Comment by Mercurial** [comment]
no pressure man, keep it up !

**Comment by SamProf** [comment]
Hey!

I introduce v 0.6.1 with supporting Razor Components.
At the beginning of the your application, usually in MainLayout.cshtml please add MatBlazorInstall component
<MatBlazorInstall />

Thank you.

**Comment by Mercurial** [comment]
awesome thanks!
