### ISSUE TITLE
FullWidth MatTextField style

### ISSUE THREAD

**Issue by enkodellc** [BlazorComponents/MatBlazor#43]
This piece of css is causing the placeholder to be too close to the input text. Is this desired? I can do my own css to change it but to me it seems like it is something that is not needed. If I remove it then it looks more correct:

`.mdc-text-field--fullwidth:not(.mdc-text-field--textarea) .mdc-text-field__input{padding: 0 }`

Before / After:

![Padding](https://user-images.githubusercontent.com/2935721/55643585-6600ad80-5788-11e9-802a-634209d5b148.jpg)

I can submit a PR if you like. Thanks

**Comment by SamProf** [comment]
You add Icon for FullWidth textbox =)
But as you remember in my code it was disabled for full-width because I have problem with icons.
Yes, you can fix css style and make PR if you want.
Thank you.

**Comment by enkodellc** [comment]
I see now that the css is coming from google directly. I am not exactly sure how to handle this. I will take a look at some options on why this is not looking correct.

**Comment by klicpjan** [comment]
I have also encountered this issue, the text is misaligned when I set FullWidth to true. It is the same piece of css that is causing the issue. Is there any "proper" way to solve this?
