### ISSUE TITLE
Select is showing native arrow?

### ISSUE THREAD

**Issue by Mercurial** [BlazorComponents/MatBlazor#48]
Select arrow seems to be showing the native one too in latest builds?

![image](https://user-images.githubusercontent.com/585569/55712393-3a4c2480-5a21-11e9-97e2-8855a89082c3.png)

**Comment by sandrohanea** [comment]
Hi!
I'll create a PR for fixing this issue :)

**Comment by SamProf** [comment]
@sandrohanea , you 2 fast 2 furious!
I will merge in the evening today. =)

**Comment by Mercurial** [comment]
awesome!
I'm using MatBlazor in this demo project by the way

https://cmx.qord.app

**Comment by SamProf** [comment]
Hey!
New version is already released https://www.nuget.org/packages/MatBlazor/0.6.17

**Comment by Mercurial** [comment]
Thank you!
