### ISSUE TITLE
Autocomplete popup width same with MatTextField

### ISSUE THREAD

**Issue by SamProf** [BlazorComponents/MatBlazor#50]
![image](https://user-images.githubusercontent.com/5611593/55743904-cebf8280-5a33-11e9-9cdf-88686d030f74.png)
@sandrohanea , width of textbox and popup should be the same

**Comment by SamProf** [comment]
I can do for myself, but if you want you can fix your control.

**Comment by sandrohanea** [comment]
Yes, I'll fix it :)
