### ISSUE TITLE
Logo and icon

### ISSUE THREAD

**Issue by SamProf** [BlazorComponents/MatBlazor#63]
If somebody have idea or opportunity or Inspiration to make logo or icons for our project, it would be good.

**Comment by enkodellc** [comment]
I like doing logos. Here is an obvious logo idea. Here are a couple examples. Only might have issues with Material / Google copyright.

![BrandBlazor_big_with_border](https://user-images.githubusercontent.com/2935721/56510867-ef7de280-64df-11e9-852b-e3cb8b45d3f4.png)

**Comment by SamProf** [comment]
Wow! Too fast! First Is really not bad.

**Comment by enkodellc** [comment]
I think this one a good one to use. It is close enough to the Material / Blazor logo but still unique enough that it shouldn't cause any conflicts with copyright. The others I did in Photoshop, This is a true vector.

![MatBlazor](https://user-images.githubusercontent.com/2935721/56536290-8ebbcd80-6512-11e9-96f3-4ec187e561ba.png)

**Comment by enkodellc** [comment]
Another option:

![MatBlazor-2](https://user-images.githubusercontent.com/2935721/56541577-fda02300-6520-11e9-9885-7200df3a5126.png)

**Comment by SamProf** [comment]
Last one is cool!

**Comment by SamProf** [comment]
Awsome logo and too fast!
